git clone git://github.com/scrooloose/nerdcommenter.git
git clone git://github.com/scrooloose/nerdtree.git
git clone git://github.com/ervandew/supertab.git
git clone git://github.com/tpope/vim-endwise.git
git clone git://github.com/tpope/vim-surround.git
git clone git://github.com/vim-ruby/vim-ruby.git
git clone git://github.com/tpope/vim-rails.git
git clone git://github.com/vim-scripts/Command-T.git
git clone git://github.com/kchmck/vim-coffee-script.git
git clone git://github.com/tpope/vim-haml.git
git clone git://github.com/tpope/vim-ragtag.git
